s=("anas superman")
# print(s.lower())
# print(s.upper())
# print(s.split())
# k="-".join(s)
# print(k)
# print(s.capitalize())
print(s.count("a"))
print(s.index("anas"))
print("\nConverted String:")
print(s.swapcase())
k=s.strip()
print(k)